class GameConfig:
    WINDOW_TITLE = "Spot Difference Game"
    WINDOW_SIZE = "1200x820"

    TOTAL_DIFFERENCES = 5
    MAX_MISTAKES = 3

    MIN_DIFFERENCE_SIZE_RATIO = 0.02
    MAX_DIFFERENCE_SIZE_RATIO = 0.04

    MIN_DIFFERENCE_SIZE_PX = 8

    ZOOM_MIN = 100
    ZOOM_MAX = 300
    ZOOM_DEFAULT = 100

    HUD_WIDTH = 150
    HUD_HEIGHT = 100

    HOVER_PREVIEW_WIDTH = 150
    HOVER_PREVIEW_HEIGHT = 100
    HOVER_CROP_HEIGHT_RATIO = 0.05

    STATUS_DURATION_MS = 2000

    CANVAS_BG = "#222222"
    PREVIEW_BG = "#111111"

    MARKER_WIDTH = 2
    REVEAL_MARKER_COLOR = "blue"
    FOUND_MARKER_COLOR = "red"
    PROXIMITY_PADDING_RATIO = 0.012